# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!
from PyQt5 import QtCore, QtGui, QtWidgets
import image
from yoi import *

class Ui_ByMelani(object):
    def setupUi(self, ByMelani):
        ByMelani.setObjectName("ByMelani")
        ByMelani.resize(577, 625)
        ByMelani.setAutoFillBackground(False)
        ByMelani.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(ByMelani)
        self.label.setGeometry(QtCore.QRect(0, 0, 581, 631))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-image: url(:/newPrefix/hm.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(ByMelani)
        self.label_3.setGeometry(QtCore.QRect(220, 50, 181, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setUnderline(True)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(ByMelani)
        self.label_4.setGeometry(QtCore.QRect(150, 80, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(ByMelani)
        self.label_5.setGeometry(QtCore.QRect(90, 130, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.Nama = QtWidgets.QLineEdit(ByMelani)
        self.Nama.setGeometry(QtCore.QRect(170, 130, 241, 21))
        self.Nama.setAutoFillBackground(False)
        self.Nama.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Nama.setObjectName("Nama")
        self.label_6 = QtWidgets.QLabel(ByMelani)
        self.label_6.setGeometry(QtCore.QRect(90, 160, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.NoMeja = QtWidgets.QComboBox(ByMelani)
        self.NoMeja.setGeometry(QtCore.QRect(170, 160, 131, 21))
        self.NoMeja.setObjectName("NoMeja")
        self.NoMeja.addItem("")
        self.NoMeja.setItemText(0, "")
        self.NoMeja.addItem("")
        self.NoMeja.addItem("")
        self.NoMeja.addItem("")
        self.NoMeja.addItem("")
        self.NoMeja.addItem("")
        self.NoMeja.addItem("")
        self.NoMeja.addItem("")
        self.NoMeja.addItem("")
        self.NoMeja.addItem("")
        self.label_7 = QtWidgets.QLabel(ByMelani)
        self.label_7.setGeometry(QtCore.QRect(90, 210, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(ByMelani)
        self.label_8.setGeometry(QtCore.QRect(90, 370, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.ABakar = QtWidgets.QCheckBox(ByMelani)
        self.ABakar.setGeometry(QtCore.QRect(90, 240, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.ABakar.setFont(font)
        self.ABakar.setObjectName("ABakar")
        self.AGoreng = QtWidgets.QCheckBox(ByMelani)
        self.AGoreng.setGeometry(QtCore.QRect(90, 270, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.AGoreng.setFont(font)
        self.AGoreng.setObjectName("AGoreng")
        self.NGoreng = QtWidgets.QCheckBox(ByMelani)
        self.NGoreng.setGeometry(QtCore.QRect(90, 300, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.NGoreng.setFont(font)
        self.NGoreng.setObjectName("NGoreng")
        self.HAbakar = QtWidgets.QLineEdit(ByMelani)
        self.HAbakar.setGeometry(QtCore.QRect(270, 240, 131, 21))
        self.HAbakar.setReadOnly(True)
        self.HAbakar.setObjectName("HAbakar")
        self.label_9 = QtWidgets.QLabel(ByMelani)
        self.label_9.setGeometry(QtCore.QRect(427, 210, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(ByMelani)
        self.label_10.setGeometry(QtCore.QRect(300, 210, 81, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_10.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.QAbakar = QtWidgets.QLineEdit(ByMelani)
        self.QAbakar.setGeometry(QtCore.QRect(420, 240, 51, 21))
        self.QAbakar.setObjectName("QAbakar")
        self.QAgoreng = QtWidgets.QLineEdit(ByMelani)
        self.QAgoreng.setGeometry(QtCore.QRect(420, 270, 51, 21))
        self.QAgoreng.setObjectName("QAgoreng")
        self.HAgoreng = QtWidgets.QLineEdit(ByMelani)
        self.HAgoreng.setGeometry(QtCore.QRect(270, 270, 131, 21))
        self.HAgoreng.setReadOnly(True)
        self.HAgoreng.setObjectName("HAgoreng")
        self.QMgoreng = QtWidgets.QLineEdit(ByMelani)
        self.QMgoreng.setGeometry(QtCore.QRect(420, 330, 51, 21))
        self.QMgoreng.setObjectName("QMgoreng")
        self.HMgoreng = QtWidgets.QLineEdit(ByMelani)
        self.HMgoreng.setGeometry(QtCore.QRect(270, 330, 131, 21))
        self.HMgoreng.setReadOnly(True)
        self.HMgoreng.setObjectName("HMgoreng")
        self.QNgoreng = QtWidgets.QLineEdit(ByMelani)
        self.QNgoreng.setGeometry(QtCore.QRect(420, 300, 51, 21))
        self.QNgoreng.setObjectName("QNgoreng")
        self.HNgoreng = QtWidgets.QLineEdit(ByMelani)
        self.HNgoreng.setGeometry(QtCore.QRect(270, 300, 131, 21))
        self.HNgoreng.setReadOnly(True)
        self.HNgoreng.setObjectName("HNgoreng")
        self.MGoreng = QtWidgets.QCheckBox(ByMelani)
        self.MGoreng.setGeometry(QtCore.QRect(90, 329, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.MGoreng.setFont(font)
        self.MGoreng.setObjectName("MGoreng")
        self.label_11 = QtWidgets.QLabel(ByMelani)
        self.label_11.setGeometry(QtCore.QRect(300, 370, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(ByMelani)
        self.label_12.setGeometry(QtCore.QRect(430, 370, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.Qej = QtWidgets.QLineEdit(ByMelani)
        self.Qej.setGeometry(QtCore.QRect(420, 460, 51, 21))
        self.Qej.setObjectName("Qej")
        self.AMineral = QtWidgets.QCheckBox(ByMelani)
        self.AMineral.setGeometry(QtCore.QRect(90, 400, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.AMineral.setFont(font)
        self.AMineral.setObjectName("AMineral")
        self.HEteh = QtWidgets.QLineEdit(ByMelani)
        self.HEteh.setGeometry(QtCore.QRect(270, 430, 131, 21))
        self.HEteh.setReadOnly(True)
        self.HEteh.setObjectName("HEteh")
        self.QAmineral = QtWidgets.QLineEdit(ByMelani)
        self.QAmineral.setGeometry(QtCore.QRect(420, 400, 51, 21))
        self.QAmineral.setObjectName("QAmineral")
        self.HAmineral = QtWidgets.QLineEdit(ByMelani)
        self.HAmineral.setGeometry(QtCore.QRect(270, 400, 131, 21))
        self.HAmineral.setReadOnly(True)
        self.HAmineral.setObjectName("HAmineral")
        self.EsJeruk = QtWidgets.QCheckBox(ByMelani)
        self.EsJeruk.setGeometry(QtCore.QRect(90, 460, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.EsJeruk.setFont(font)
        self.EsJeruk.setObjectName("EsJeruk")
        self.HEjeruk = QtWidgets.QLineEdit(ByMelani)
        self.HEjeruk.setGeometry(QtCore.QRect(270, 460, 131, 21))
        self.HEjeruk.setReadOnly(True)
        self.HEjeruk.setObjectName("HEjeruk")
        self.EsTeh = QtWidgets.QCheckBox(ByMelani)
        self.EsTeh.setGeometry(QtCore.QRect(90, 430, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.EsTeh.setFont(font)
        self.EsTeh.setObjectName("EsTeh")
        self.QEteh = QtWidgets.QLineEdit(ByMelani)
        self.QEteh.setGeometry(QtCore.QRect(420, 430, 51, 21))
        self.QEteh.setObjectName("QEteh")
        self.TotalHarga = QtWidgets.QPushButton(ByMelani)
        self.TotalHarga.setGeometry(QtCore.QRect(154, 507, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.TotalHarga.setFont(font)
        self.TotalHarga.setObjectName("TotalHarga")
        self.THarga = QtWidgets.QLineEdit(ByMelani)
        self.THarga.setGeometry(QtCore.QRect(280, 507, 131, 30))
        self.THarga.setReadOnly(True)
        self.THarga.setObjectName("THarga")
        self.order = QtWidgets.QPushButton(ByMelani)
        self.order.setGeometry(QtCore.QRect(280, 560, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setBold(True)
        font.setWeight(75)
        self.order.setFont(font)
        self.order.setObjectName("order")
        self.batal = QtWidgets.QPushButton(ByMelani)
        self.batal.setGeometry(QtCore.QRect(370, 560, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setBold(True)
        font.setWeight(75)
        self.batal.setFont(font)
        self.batal.setObjectName("batal")
        self.keluar = QtWidgets.QPushButton(ByMelani)
        self.keluar.setGeometry(QtCore.QRect(460, 560, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setBold(True)
        font.setWeight(75)
        self.keluar.setFont(font)
        self.keluar.setObjectName("keluar")

        self.batal.clicked.connect(self.setBatal)
        self.TotalHarga.clicked.connect(self.setTotal)
        self.order.clicked.connect(self.klikk)
        self.setHarga()

        self.retranslateUi(ByMelani)
        self.keluar.clicked.connect(ByMelani.close)
        QtCore.QMetaObject.connectSlotsByName(ByMelani)

    def setHarga(self):
        self.HAbakar.setText("13000")
        self.HAgoreng.setText("13000")
        self.HNgoreng.setText("12000")
        self.HMgoreng.setText("10000")
        self.HAmineral.setText("3000")
        self.HEteh.setText("3500")
        self.HEjeruk.setText("4000")

    def setBatal(self):
        self.NoMeja.setCurrentIndex(0)
        self.Nama.setText("")
        self.ABakar.setChecked(False)
        self.QAbakar.setText("")
        self.AGoreng.setChecked(False)
        self.QAgoreng.setText("")
        self.NGoreng.setChecked(False)
        self.QNgoreng.setText("")
        self.MGoreng.setChecked(False)
        self.QMgoreng.setText("")
        self.AMineral.setChecked(False)
        self.QAmineral.setText("")
        self.EsTeh.setChecked(False)
        self.QEteh.setText("")
        self.EsJeruk.setChecked(False)
        self.Qej.setText("")
        self.THarga.setText("")

    def setTotal(self):
        HAB = 0
        HNG = 0
        HAG = 0
        HMG = 0
        HAM = 0
        HET = 0
        HEJ = 0

        QAB = 0
        QAG = 0
        QNG = 0
        QMG = 0
        QAM = 0
        QET = 0
        QEJ = 0

        if self.ABakar.isChecked():
            self.HAbakar.setText("13000")
            HAB1 = self.HAbakar.text()
            HAB = eval(HAB1)
            QAB1 = self.QAbakar.text()
            QAB = eval(QAB1)

        AB = HAB * QAB

        if self.AGoreng.isChecked():
            self.HAgoreng.setText("13000")
            HAG1 = self.HAgoreng.text()
            HAG = eval(HAG1)
            QAG1 = self.QAgoreng.text()
            QAG = eval(QAG1)

        AG = HAG * QAG

        if self.NGoreng.isChecked():
            self.HNgoreng.setText("12000")
            HNG1 = self.HNgoreng.text()
            HNG = eval(HNG1)
            QNG1 = self.QNgoreng.text()
            QNG = eval(QNG1)

        NG = HNG * QNG

        if self.MGoreng.isChecked():
            self.HMgoreng.setText("10000")
            HMG1 = self.HMgoreng.text()
            HMG = eval(HMG1)
            QMG1 = self.QMgoreng.text()
            QMG = eval(QMG1)

        MG = HMG * QMG

        if self.AMineral.isChecked():
            self.HAmineral.setText("3000")
            HAM1 = self.HAmineral.text()
            HAM = eval(HAM1)
            QAM1 = self.QAmineral.text()
            QAM = eval(QAM1)

        AM = HAM * QAM

        if self.EsTeh.isChecked():
            self.HEteh.setText("3500")
            HET1 = self.HEteh.text()
            HET = eval(HET1)
            QET1 = self.QEteh.text()
            QET = eval(QET1)

        ET = HET * QET

        if self.EsJeruk.isChecked():
            self.HEjeruk.setText("4000")
            HEJ1 = self.HEjeruk.text()
            HEJ = eval(HEJ1)
            QEJ1 = self.Qej.text()
            QEJ = eval(QEJ1)

        EJ = HEJ * QEJ

        TOT = AB + AG + NG + MG + AM + ET + EJ
        self.THarga.setText(str(TOT))

    def klikk(self):
        Dialog = QtWidgets.QDialog()
        ui = Ui_Dialog()
        ui.setupUi(Dialog)
        Dialog.show()
        sh = Dialog.exec_()
        self.setBatal()

        if sh == QtWidgets.QDialog.Rejected:
            self.setBatal()

    def retranslateUi(self, ByMelani):
        _translate = QtCore.QCoreApplication.translate
        ByMelani.setWindowTitle(_translate("ByMelani", "Form"))
        self.label_3.setText(_translate("ByMelani", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Rockwell\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#00007f;\">DAFTAR MENU</span></p></body></html>"))
        self.label_4.setText(_translate("ByMelani", "<html><head/><body><p align=\"center\"><span style=\" color:#00007f;\">WW CHICKEN DINER RESTO</span></p></body></html>"))
        self.label_5.setText(_translate("ByMelani", "Nama "))
        self.label_6.setText(_translate("ByMelani", "No. Meja "))
        self.NoMeja.setItemText(1, _translate("ByMelani", "Bungkus"))
        self.NoMeja.setItemText(2, _translate("ByMelani", "1"))
        self.NoMeja.setItemText(3, _translate("ByMelani", "2"))
        self.NoMeja.setItemText(4, _translate("ByMelani", "3"))
        self.NoMeja.setItemText(5, _translate("ByMelani", "4"))
        self.NoMeja.setItemText(6, _translate("ByMelani", "5"))
        self.NoMeja.setItemText(7, _translate("ByMelani", "6"))
        self.NoMeja.setItemText(8, _translate("ByMelani", "7"))
        self.NoMeja.setItemText(9, _translate("ByMelani", "8"))
        self.label_7.setText(_translate("ByMelani", "Makanan"))
        self.label_8.setText(_translate("ByMelani", "Minuman"))
        self.ABakar.setText(_translate("ByMelani", "Nasi Ayam Bakar"))
        self.AGoreng.setText(_translate("ByMelani", "Nasi Ayam Goreng"))
        self.NGoreng.setText(_translate("ByMelani", "Nasi Goreng Ayam"))
        self.label_9.setText(_translate("ByMelani", "Qty"))
        self.label_10.setText(_translate("ByMelani", "<html><head/><body><p><span style=\" color:#000000;\">Harga</span></p></body></html>"))
        self.MGoreng.setText(_translate("ByMelani", "Mie Goreng"))
        self.label_11.setText(_translate("ByMelani", "Harga"))
        self.label_12.setText(_translate("ByMelani", "Qty"))
        self.AMineral.setText(_translate("ByMelani", "Air Mineral"))
        self.EsJeruk.setText(_translate("ByMelani", "Es Jeruk"))
        self.EsTeh.setText(_translate("ByMelani", "Es Teh"))
        self.TotalHarga.setText(_translate("ByMelani", "Total Harga"))
        self.order.setText(_translate("ByMelani", "ORDER"))
        self.batal.setText(_translate("ByMelani", "BATAL"))
        self.keluar.setText(_translate("ByMelani", "KELUAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ByMelani = QtWidgets.QWidget()
    ui = Ui_ByMelani()
    ui.setupUi(ByMelani)
    ByMelani.show()
    sys.exit(app.exec_())

